# Generated by Django 5.2.1 on 2025-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_has_fingerprint_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_agreed',
            field=models.BooleanField(default=True),
        ),
    ]
