# Generated by Django 5.2.1 on 2025-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_feedback_image_alter_feedback_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_cycles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
