# Generated by Django 5.2.1 on 2025-08-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_blocked_until_customuser_failed_cycles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_until',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='failed_cycles',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pin_attempts',
        ),
    ]
