# Generated by Django 5.2.1 on 2025-09-07 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_blocked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_fingerprint_enabled',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(default='No message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
