# Generated by Django 5.2.1 on 2025-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pin_code',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
