# Generated by Django 5.2.1 on 2025-06-14 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_number_card_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_received', to='transactions.card')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_sent', to='transactions.card')),
            ],
        ),
    ]
