# Generated by Django 5.2.1 on 2025-06-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_servicepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='service_type',
            field=models.CharField(choices=[('electricity', 'Elektr'), ('water', 'Suv'), ('gas', 'Gaz'), ('internet', 'Internet')], default='Kommunal', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('Ucell', 'Ucell'), ('Beeline', 'Beeline'), ('Mobiuz', 'Mobiuz'), ('Humans', 'Humans'), ('Uzmobile', 'Uzmobile')], max_length=20)),
                ('phone_number', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
