# Generated by Django 5.2.1 on 2025-06-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_servicepayment_service_type_mobilepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('mobile', 'Mobil to‘lov'), ('service', 'Kommunal xizmat')], max_length=10, unique=True)),
                ('service_fee_percent', models.DecimalField(decimal_places=2, help_text='Foydalanuvchidan olinadigan komissiya (%)', max_digits=5)),
                ('click_fee_percent', models.DecimalField(decimal_places=2, help_text='Click yoki provayder ulushi (%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferProfitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('your_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_log', to='transactions.transfertransaction')),
            ],
        ),
    ]
