# Generated by Django 5.2.1 on 2025-07-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_pin_code'),
        ('transactions', '0006_commissionsetting_transferprofitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrtoken',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card'),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='card.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='card.card'),
        ),
        migrations.AlterField(
            model_name='nfctransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_sent', to='card.card'),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='card.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='card.card'),
        ),
        migrations.AlterField(
            model_name='nfctransaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_received', to='card.card'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
